USE [QLVT_DATHANG]
GO

/****** Object:  StoredProcedure [dbo].[sp_HoatDongNhanVien]    Script Date: 5/30/2022 3:12:24 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[sp_HoatDongNhanVien] @MANV int,
@LOAI nvarchar(4),
@DATEFROM DATETIME,
@DATETO DATETIME
AS
BEGIN
	IF( @LOAI = 'NHAP')
	BEGIN
		SELECT FORMAT(PN.NGAY,'MM-yyyy') AS THANGNAM, -- Group theo mẫu
				PN.NGAY, 
				PN.MAPN AS MAPHIEU,
				TENVT, 
				TENKHO, 
				SOLUONG,
				DONGIA,
				SOLUONG * DONGIA AS TRIGIA
		FROM (SELECT NGAY, 
					MAPN,
					TENKHO = ( SELECT TENKHO FROM Kho WHERE P.MAKHO = Kho.MAKHO )
				FROM PhieuNhap AS P
				WHERE NGAY BETWEEN @DATEFROM AND @DATETO 
				AND MANV = @MANV )PN,
				CTPN,
				(SELECT MAVT, TENVT FROM Vattu ) VT
		WHERE PN.MAPN =CTPN.MAPN
		AND VT.MAVT = CTPN.MAVT
		ORDER BY NGAY, MAPHIEU, TENVT
	END

	ELSE
	BEGIN
		SELECT FORMAT(PX.NGAY,'MM-yyyy') AS THANGNAM, -- Group theo mẫu
				PX.NGAY, 
				PX.MAPX AS MAPHIEU,
				TENVT, 
				TENKHO, 
				SOLUONG,
				SOLUONG * DONGIA AS TRIGIA
		FROM (SELECT NGAY, 
					MAPX,
					TENKHO = ( SELECT TENKHO FROM Kho WHERE P.MAKHO = Kho.MAKHO )
				FROM PhieuXuat AS P
				WHERE NGAY BETWEEN @DATEFROM AND @DATETO 
				AND MANV = @MANV )PX,
				CTPX,
				(SELECT MAVT, TENVT FROM Vattu ) VT
		WHERE PX.MAPX =CTPX.MAPX
		AND VT.MAVT = CTPX.MAVT
		ORDER BY NGAY, MAPHIEU, TENVT
	END
END
GO

